### ISSUE TITLE
MFMT FTP command support.

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/pyftpdlib#201]
_From [btimby@gmail.com](https://code.google.com/u/btimby@gmail.com/) on January 20, 2012 22:47:34_

```
Any thoughts on implementing MFMT and friends? 
http://www.omz13.com/downloads/draft-somers-ftp-mfxx-02.html#MFMT These are 
useful for file synchronization over FTP.

I had someone request it and might go ahead and send a patch if you are open to 
it. Otherwise if you have feedback for or against, I would like to hear it.

Thanks.
```

_Original issue: http://code.google.com/p/pyftpdlib/issues/detail?id=201_

**Comment by btimby** [comment]
@giampaolo Do you still have this patch for MFMT around? I assume the Google Code exporter did not include it here, and I can't find it.

Thanks.

**Comment by giampaolo** [comment]
Hey Ben, glad to hear from you! =) 
Oh! It seems Google Code is definitively gone for good, and no, I no longer have that patch. :(
More or less, in order to implement this:

1) The filesystem class should expose an `utime` method: https://docs.python.org/3/library/os.html#os.utime

2) The authorizer has to expose a new permission. Right now we have

```
    read_perms = "elr"
    write_perms = "adfmwM"
```

Being MFMT an "unofficial" command the new letter has to be capitalized (maybe "T"?). 

3) As per https://tools.ietf.org/html/draft-somers-ftp-mfxx-04 there's also MFMC (modify creation time); not sure if we want that too but if I'm not mistaken file creation time is not supported on UNIX (but it should be on Windows). I'd be OK with implementing MFMT only for now, and think about MFMC later, and if we do it can simply be a no-op on UNIX.

This is the rough idea. I'm not sure I'll have time to work on this anytime soon though as I'm going to China and will stay "out" for the next couple of months.

**Comment by btimby** [comment]
Thanks for the reply, I am not sure if we need this or not, I really just wanted to know if you had the old patch or not (my email does not go back that far). So don't worry about this at all.

Have fun in China, I am sure it will be quite an experience.

**Comment by giampaolo** [comment]
Implemented in https://github.com/giampaolo/pyftpdlib/issues/434.
