### ISSUE TITLE
memory leak in Multiprocess mode

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/pyftpdlib#263]
_From [timebug....@gmail.com](https://code.google.com/u/117034039683428790169/) on June 12, 2013 15:59:36_

```
What steps will reproduce the problem?  
1. python multi_proc_ftp.py
2. python ftp_test.py (ftp.login, ftp.pwd, ftp.quit)
3. after a few minutes & run `top` cmd 

What is the expected output?  


What do you see instead?  
PID USER      PR  NI  VIRT  RES  SHR S &#37;CPU &#37;MEM    TIME+  COMMAND      

 4821 root      20   0  496m 446m 3640 R   46 11.3  15:02.19 python

What version of pyftpdlib are you using? On what operating system? Which Python version?

pyftpdlib 1.2.0
CPython 2.7.3
Fedora 18 x86_64 Please provide any additional information below.
```

**Attachment:** [ftp_test.py](http://code.google.com/p/pyftpdlib/issues/detail?id=263)

_Original issue: http://code.google.com/p/pyftpdlib/issues/detail?id=263_

**Comment by yuyang733** [comment]
Hello, 
        I recently used it to develop my own server program, however, I found that memory consumption is very fast in MultiprocessFTPServer mode. 
        I suspect it caused by the memory leak. 
       So, I want to know whether the bug is fixed in Github?
       The attachment link you provided may be invalid.
