### ISSUE TITLE
Is this a typo?

### ISSUE THREAD

**Issue by niccokunzmann** [giampaolo/pyftpdlib#306]
https://github.com/giampaolo/pyftpdlib/blob/master/pyftpdlib/authorizers.py#L784

    class WindowsAuthorizer(_Base, BaseWindowsAuthorizer):
    [...]
        >>> auth = UnixAuthorizer(rejected_users=["Administrator"])

UnixAuthorizer in the WindowsAuthorizer docs?

**Comment by giampaolo** [comment]
Yeah, that's a typo. I just fixed it. Thanks.
