### ISSUE TITLE
Terminated TLS connection causes 100% CPU usage

### ISSUE THREAD

**Issue by j883376** [giampaolo/pyftpdlib#333]
When a client has connected over TLS and the connection is not cleanly closed, the server will use 100% CPU until it is restarted. I was able to reliably reproduce this on the latest master version.

Steps to reproduce:
1. Start a server and connect with TLS
2. Forcibly kill the FTP client via kill -9 or the task manager on Windows

**Comment by giampaolo** [comment]
I made many changes to SSL stuff which may have fixed this issue. Could you please try with latest GIT code?

**Comment by j883376** [comment]
Sorry for the delay. I was able to confirm that this is no longer an issue with newer revisions. Thank you.
