### ISSUE TITLE
Client certificate authentication

### ISSUE THREAD

**Issue by mdineen** [giampaolo/pyftpdlib#336]
Is there a way to support client certificates for authentication in the library?

**Comment by giampaolo** [comment]
I'm no (py)OpenSSL expert. What do you mean by that exactly? That you pass a certfile to the server, then the client has the same certificate and only clients using that certificate will be able to login?
Currently that is not implemented and honestly right now I have no idea how to do that.

**Comment by mdineen** [comment]
No worries, we're going to use SFTP.

**Comment by giampaolo** [comment]
Solved by #428
