### ISSUE TITLE
Control connection timed out

### ISSUE THREAD

**Issue by googley** [giampaolo/pyftpdlib#375]
Hi,

I think it's not a bug but i can't find any parameter.
How to change the control connection  time out ?

**Comment by giampaolo** [comment]
`PassiveDTP.timeout` and `ActiveDTP.timeout` class attributes control the timeout of PASV and PORT commands respectively. Set them to `0` or `None` to disable timeout (not recommended).

**Comment by googley** [comment]
How? It doesn't work for me...
I tried
```python
PassiveDTP.timeout = None
```
```python
handler.passive_dtp = PassiveDTP
handler.passive_dtp.timeout = None
```
```python
server.passive_dtp = PassiveDTP
server.passive_dtp.timeout = None
```

**Comment by giampaolo** [comment]
`handler.passive_dtp.timeout = None` should do the trick.
If not try:

```
import pyftpdlib.handlers
pyftpdlib.handlers.PassiveDTP.timeout = None

# ...do your stuff here 
```

Anyway, I do not recommend disabling the timeout. You risk to end up with lots of pending open sockets, run out of file descriptors and finally not being able to accept new connections (DoS).

**Comment by googley** [comment]
```python
import pyftpdlib.handlers
pyftpdlib.handlers.PassiveDTP.timeout = None
```
It works fine!
Of course it's for testing...
