### ISSUE TITLE
SSLv2, SSLv3, errno 0 on conn.unwrap, and more...

### ISSUE THREAD

**Issue by frispete** [giampaolo/pyftpdlib#382]
Dear Giampaolo, thanks for this nice package. 
Before a submission to some official repos, I'm packaging it in the openSUSE build service:
https://build.opensuse.org/package/show/home:frispete:python/python-pyftpdlib

Unfortunately, I wasn't able to package it verbatim due to a couple of issues.
It boils down to tests, that fail on TRAVIS, fail on the build service as well (more often than not).
Other tests fail occasionally, which is a bit annoying. Do you have an explanation for this behaviour?

One issue with SSLv3 should be of general interest, since newer Python builds tend to disable it altogether (Debian and openSUSE at least):
https://build.opensuse.org/package/view_file/home:frispete:python/python-pyftpdlib/pyftpdlib-handle-missing-SSLv3.diff?expand=1

It would be nice to take the patch directly.

Cheers,
Pete

**Comment by giampaolo** [comment]
Hello there and sorry for the big delay in responding. I am stabilizing tests as of #386. I am closing this one out as a duplicate.
