### ISSUE TITLE
In on_disconnect have login id of user being disconnected

### ISSUE THREAD

**Issue by pyvotal-cguers** [giampaolo/pyftpdlib#383]
Where can I obtain the **login id** of the user being disconnected after a timeout (when the user is disconnected after a period of time of inactivity)? I need this information to use in the **on_disconnect** hook.

Thanks!

**Comment by TheBlusky** [comment]
Same question here :-) Any idea ?

**Comment by giampaolo** [comment]
Sorry for the incredibly late reply. The information should still stored be stored in `self.username` attribute.
