### ISSUE TITLE
Determine if connection coming in is SSL or not

### ISSUE THREAD

**Issue by pyvotal-cguers** [giampaolo/pyftpdlib#384]
How can I know at login time whether the user is coming in via a secure TLS connection or not? I would like to have access to this information in the **on_login** hook and know by user, by each connection doming in.

Thanks!

**Comment by Ryanb58** [comment]
I know this is is from quite a while ago.. but... 

@pyvotal-cguers I'm not sure if this will work, but there is a method you can call on the socket to get the version name.

```
self.socket.get_protocol_version_name()
```

This will return an Attribute Error if the user is connecting via clear text else it'll return the TLS version they are connecting by. I believe only TLS 1.2 is secure currently as known vulnerabilities have been found for the previous versions.

**Comment by pyvotal-cguers** [comment]
This was from a while ago, but I had not found a way of addressing it. I will give this a try. Thanks!!!

**Comment by Ryanb58** [comment]
@pyvotal-cguers No problem. Let me know if it works for you.

Also, @giampaolo  mentioned to me that this is probably best going inside of the `handle_ssl_established` method. I am personally using it inside of a method called `ftp_PASS` myself.

**Comment by giampaolo** [comment]
Sorry for not replying to this but it totally slipped under my radar.
The safest way to check whether you're using a SSL connection is by checking the socket object instance. From anywhere withing the handler instance you just do:

```
from OpenSSL import SSL
isinstance(self.socket, SSL.Connection)
```
