### ISSUE TITLE
File size or bytes transferred after send or receive

### ISSUE THREAD

**Issue by pyvotal-cguers** [giampaolo/pyftpdlib#385]
Is there a way to get from pyftpdlib the number of bytes transferred after a file was received or sent (**on_file_sent** and **on_file_received**)... or do I need to get this information from the OS?

**Comment by sdrees** [comment]
@pyvotal-cguers: Isn't there this `self.get_transmitted_bytes()`? I skimmed over the `handlers.py` file ...

**Comment by giampaolo** [comment]
You have two ways to get file size. From  `DTPHandler.get_transmitted_bytes()` or from `FTPHandler`'s `on_file_*` callbacks:
http://pythonhosted.org/pyftpdlib/api.html#pyftpdlib.handlers.FTPHandler.on_file_sent. These will give you the absolute path of the file and you can use `os.path.getsize()` against them.
