### ISSUE TITLE
Travis error on Python2.6

### ISSUE THREAD

**Issue by lurch** [giampaolo/pyftpdlib#401]
Looking at https://travis-ci.org/giampaolo/pyftpdlib/jobs/166424021 it's failing with `AttributeError: 'module' object has no attribute 'OrderedDict'` somewhere deep within the flake8 code.

I did a bit of searching and found https://flake8.pycqa.org/en/latest/release-notes/3.0.0.html from which it looks like flake8 2.6.2 was the last version to support Python 2.6, so perhaps your `tox.ini` needs to be updated as necessary, and then maybe the Travis tests would pass on Python 2.6?

And on a side-note: Why does Travis test Python versions 2.6, 2.7, 3.3, 3.4 and 3.5, but Appveyor only test 2.7, 3.3 and 3.4? (and `tox.ini` includes py32, which neither of `.travis.yml` or `appveyor.yml` do)
Found these links, which may be useful:
https://docs.travis-ci.com/user/languages/python/
https://www.appveyor.com/docs/installed-software/#python

**Comment by gliptak** [comment]
Travis and Python 2.6 is no longer used. Consider closing
