### ISSUE TITLE
socket.error: [Errno 9] Bad file descriptor after server restart

### ISSUE THREAD

**Issue by demosthenesk** [giampaolo/pyftpdlib#404]
If write in code,

    server.serve_forever()
    server.close_all()
    server.serve_forever()

1) The server starts. with server.serve_forever()
2) Press Ctl+C to kill server loop
3) Then you get socket.error: [Errno 9] Bad file descriptor
[test.py.zip](https://github.com/giampaolo/pyftpdlib/files/562176/test.py.zip)

**Comment by giampaolo** [comment]
That's because the server is not supposed to be restarted. It can only be started and shut down once.
What you can do is create a new FTPServer instance from scratch.

**Comment by lurch** [comment]
> That's because the server is not supposed to be restarted. It can only be started and shut down once.

Would it be worth detecting that condition, and throwing a more helpful exception message?

**Comment by demosthenesk** [comment]
here is the output of test.py which i have attached in previous message:

[I 2016-11-01 14:08:17] >>> starting FTP server on 0.0.0.0:21, pid=4590 <<<
[I 2016-11-01 14:08:17] concurrency model: async
[I 2016-11-01 14:08:17] masquerade (NAT) address: None
[I 2016-11-01 14:08:17] passive ports: None
^C[I 2016-11-01 14:08:18] received interrupt signal
[I 2016-11-01 14:08:18] >>> shutting down FTP server (1 active socket fds) <<<
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    main()
  File "test.py", line 16, in main
    server.serve_forever()
  File "/usr/local/lib/python2.7/dist-packages/pyftpdlib/servers.py", line 205, in serve_forever
    self._log_start()
  File "/usr/local/lib/python2.7/dist-packages/pyftpdlib/servers.py", line 152, in _log_start
    addr = self.address
  File "/usr/local/lib/python2.7/dist-packages/pyftpdlib/servers.py", line 119, in address
    return self.socket.getsockname()[:2]
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
  File "/usr/lib/python2.7/socket.py", line 174, in _dummy
    raise error(EBADF, 'Bad file descriptor')
socket.error: [Errno 9] Bad file descriptor
