### ISSUE TITLE
Question: When is the release 1.6.0 planned ? 

### ISSUE THREAD

**Issue by atvise** [giampaolo/pyftpdlib#418]
Hi,

first of all: great library ! 

Do any of you know when and if the release 1.6.0 is planned ?

Greetings,
atvise

**Comment by giampaolo** [comment]
I've been kinda lazy in the past months re. pyftpdlib. There is already the possibility to make a new release soon as HISTORY file (https://github.com/giampaolo/pyftpdlib/blob/master/HISTORY.rst) already has 2 enhancements and 3 bugfixes). I only would like to add #417 and then make a new release. Not sure about the ETA but I hope it'll be soon.
