### ISSUE TITLE
Ctrl-C doesn't exit FTPServer until ftp action is handled

### ISSUE THREAD

**Issue by CeruleanSky** [giampaolo/pyftpdlib#431]
On windows at least running ```python -m pyftpdlib``` with python 2&3, ctrl-c does not shutdown the process until a ftp command is received.

As experiments, I tried throwing a sys.exit() under this line:  
https://github.com/giampaolo/pyftpdlib/blob/ab699b5f89223e03593f3e004d6a370b4c2e5308/pyftpdlib/servers.py#L208
And a except KeyboardInterrupt: sys.exit() under this line:  
https://github.com/giampaolo/pyftpdlib/blob/ab699b5f89223e03593f3e004d6a370b4c2e5308/pyftpdlib/__main__.py#L94

But neither worked. I figured it would be better at that point to file this issue so the appropriate modification in the proper place could be made since it may or may not require trivial considerations.

**Comment by giampaolo** [comment]
This is a known problem on Windows where `select()` (and I suppose also other syscalls) cannot be interrupted. The easiest solution is to pass a timeout to it as in `server.serve_forever(timeout=2)`.

**Comment by giampaolo** [comment]
Fixed.

**Comment by TheSil** [comment]
Just a note regarding this, I've added this proposal https://bugs.python.org/issue34934 that would make it interruptible. Will probably get rejected, but we will see.
