### ISSUE TITLE
Broken documentation links

### ISSUE THREAD

**Issue by DavidA2014** [giampaolo/pyftpdlib#440]
[https://pythonhosted.org/pyftpdlib/](url) is broken.

Also, on [https://github.com/giampaolo/pyftpdlib/blob/master/docs/faqs.rst#how-can-i-run-long-running-tasks-without-blocking-the-server](url) the link [https://github.com/giampaolo/pyftpdlib/blob/master/docs/tutorial.html#changing-the-concurrency-model](url) is broken.

**Comment by giampaolo** [comment]
Doc is now hosted at http://pyftpdlib.readthedocs.io/en/latest/

**Comment by DavidA2014** [comment]
Thank you. Unfortunately, Google comes up with [https://pythonhosted.org/pyftpdlib](url) when I search for pyftpdlib.
