### ISSUE TITLE
Add Users Without Restarting Server

### ISSUE THREAD

**Issue by baberuth22** [giampaolo/pyftpdlib#443]
How do I add users without restarting my ubuntu server?

Do I restart the FTP sever only?   If so, how do I restart the FTP server?

Is there a way to dynamically read users from a file?

Stupid question I'm sure, but I am new to python dev and hosting my own server.

**Comment by giampaolo** [comment]
There are different strategies to achieve this. The main thing to keep in mind is that what controls the authentication logic is the authorizer class, which by default is `DummyAuthorizer`:
https://github.com/giampaolo/pyftpdlib/blob/master/pyftpdlib/authorizers.py#L53-L264

By default `DummyAuthorizer` stores users (and their passwords, homes, perms, etc.) in memory. When you write a custom authorizer what you typically do is replace "memory" with "something else": it may be a file, a db, UNIX shadow password db, an HTTP request to an external service or whatever.

One way to achieve this is, therefore, writing a subclass of `DummyAuthorizer` and make it read users data from a file.

**Comment by baberuth22** [comment]
Thanks for the quick response as well as the awesome library @giampaolo !

With limited python knowledge, it is a tall order for me to subclass the DummyAuthorizer.  I will, however, do some research and attempt a subclass.

I created my server based upon this tutorial https://serverpilot.io/community/articles/how-to-run-a-simple-ftp-server.html

I added additional users by duplicating and editing this line.

`authorizer.add_user(FTP_USER, FTP_PASSWORD, FTP_DIRECTORY, perm='elradfmw')`

My FTP server starts on reboot because of this command.  

`@reboot python /srv/users/serverpilot/ftpserver.py >>/srv/users/serverpilot/ftpserver.log 2>&1`

So if enter the following into the terminal, will the FTP server restart and new users added?
`python /srv/users/serverpilot/ftpserver.py >>/srv/users/serverpilot/ftpserver.log 2>&1`

For now, I am just looking for the simplest approach to add users with minimal interruption to the server.  Thanks again.

**Comment by baberuth22** [comment]
It looks like rerunning the ftpserver.py script does not restart the ftp server and add new users.   I suppose I have to stop the ftp server first.   Not sure how though.

**Comment by baberuth22** [comment]
It seems to stop the FTP server, I use the kill command with the FTP server processes' PID, which I can find with this command:

ps -ef | grep ftpserver | grep -v grep | awk '{print $2}'

**Comment by giampaolo** [comment]
Yes, if you want to update users right now the only method you have is update `ftpserver.py` and restart the python process. As for subclassing DummyAuthorizer, it's not exactly easy if you're new to Python.

**Comment by apidirect** [comment]
I am still looking for a way to add users without restarting the server.   Do you think you could accomplish this?   Is it even possible?
