### ISSUE TITLE
I have 3 net adapter, how can i create a ftp server to bind all ip address?

### ISSUE THREAD

**Issue by jekoie** [giampaolo/pyftpdlib#446]
I have 3 net adapter, how can i create a ftp server to bind all ip address???

**Comment by kognate** [comment]
To bind a server to all IP addresses you can use `0.0.0.0`.

For example,  

```
server = FTPServer(("0.0.0.0", 21), handler)
```

will bind the server to all IPV4 addresses.  "0.0.0.0" is `INADDR_ANY` and you can read more about that here https://stackoverflow.com/questions/16508685/understanding-inaddr-any-for-socket-programming

**Comment by jekoie** [comment]
Thanks many much.
