### ISSUE TITLE
ac_out_buffer_size has no effect when sendfile is not valid

### ISSUE THREAD

**Issue by xiangxw** [giampaolo/pyftpdlib#450]
sendfile is not installed.

**Comment by giampaolo** [comment]
What do you mean? What is the problem?

**Comment by xiangxw** [comment]
```
dtp_handler = DTPHandler
dtp_handler.ac_out_buffer_size = 1024 * 1024 * 2
```
I set ```ac_out_buffer_size``` to ```1024*1024*2```, and it has not effect. Seems ```ac_out_buffer_size``` is not valid when ```sendfile``` is disabled.

**Comment by giampaolo** [comment]
How are you testing this? Why do you think it's ignored?

**Comment by xiangxw** [comment]
When I set ```ac_in_buffer_size```, the upload speed increases. But the download speed does not change when I set ```ac_out_buffer_size```.
Besides, from the code, ```ac_out_buffer_size``` is only used in function ```initiate_sendfile``` of ```pyftpdlib/handlers.py```, so maybe it's not valid when ```sendfile``` is disabled?

**Comment by giampaolo** [comment]
It is also used in `asynchat` module, which is in the standard library. I assure you it is used. =)
Currently the 65536 default is supposed to be a good compromise in terms of performance.
