### ISSUE TITLE
using 'localhost' on win 7 command line fails

### ISSUE THREAD

**Issue by marcDesm** [giampaolo/pyftpdlib#451]
The following command line does not lead to port 127.0.0.1:8021 getting used
python -m pyftpdlib -i localhost -p 8021 -D
[I 2018-01-20 17:35:16] >>> starting FTP server on ::1:8021, pid=9792 <<<

At least not on a win7 command console.
I had to use this instead:

python -m pyftpdlib -i 127.0.0.1 -p 8021

**Comment by giampaolo** [comment]
Apparently that's because `socket.bind("localhost")` on Windows assumes IPv6 instead of IPv4. `"::1:8021"` indicates so. I think it's worth it to force IPv4 by default.

**Comment by marcDesm** [comment]
OK thanks
I just started check pyftpdlib (using the command line on win7)

I got stuck with the "150 File status okay" on my first test.

Turns out I started the server from a directory path that has a space.
That's a bit of  trap ...
 Marc Desmarais
