### ISSUE TITLE
How to get date and time as prefix to log messages?

### ISSUE THREAD

**Issue by marcDesm** [giampaolo/pyftpdlib#453]
I see in your documentation that example logs start with data and time.
But I don't get that.  My output is shown below.

INFO:pyftpdlib:>>> starting FTP server on 0.0.0.0:21, pid=7220 <<<
INFO:pyftpdlib:concurrency model: async
INFO:pyftpdlib:masquerade (NAT) address: None
INFO:pyftpdlib:passive ports: None
INFO:pyftpdlib:127.0.0.1:50973-[] FTP session opened (connect)
INFO:pyftpdlib:127.0.0.1:50973-[ba5020blue] USER 'ba5020blue' logged in.

**Comment by giampaolo** [comment]
What's your code?

**Comment by marcDesm** [comment]
I just added this, and that did the trick.  You may want to add that in your example.  Great library BTW.

logging.basicConfig(format='%(asctime)s %(message)s')

**Comment by giampaolo** [comment]
Thanks. If you avoid calling `logging.basicConfig` in the first place you'll automatically get colored logs.

**Comment by marcDesm** [comment]
ah, that was the problem, I initially just caled basicConfig to control the level, and that clobbered the dates
 Marc Desmarais
