### ISSUE TITLE
propagate errors back to user (ftp client such as filezilla)

### ISSUE THREAD

**Issue by vangalamaheshh** [giampaolo/pyftpdlib#456]
@giampaolo -

I have a use case where I'm allowing only gzip files to be uploaded. Failing which, I need to inform user that given file is not gzip. What do you think is the solution for this?

I have tried several ways but not succeeded.

1) I have tried with CustomPassiveDTP with extended handle_error method. It did not work.
2) I have tried calling self.handle_error("some msg") right with in on_file_received method, but no success.

Alternatively, I wanted to atleast inform every user after successful login that the policy is to upload only gzip files. However, 
1) msg_login feature within DummyAuthorizer is not resulting in the filezilla.

Any thoughts from you are greatly appreciated.

Thanks,
Mahesh

**Comment by giampaolo** [comment]
Not tested:

```python
from pyftpdlib.handlers import FTPHandler


class MyHandler(FTPHandler):

    def ftp_STOR(self, file, mode='w'):
        if not file.endswith('.gz'):
            self.respond('425 only .gz files are allowed')
        else:
            return super(MyHandler, self).ftp_STOR(file, mode=mode)

...  # rest of your code here
```
