### ISSUE TITLE
embedded sytem fails to ftp boot, could be its half duplex configuration

### ISSUE THREAD

**Issue by marcDesm** [giampaolo/pyftpdlib#458]
I'm running an Python 2.7 program that offers ftp service using pyftpdlib on a win7 machine.
The PC is directly connected to an embedded system, using a cross over Ethernet cable. When the embedded system powers up, it attempts to load an image residing on the PC disk, using the FTP protocol.  Currently, with the  embedded system having its network interface configured to full duplex, the boot up process works well,  But when the  embedded system's NIC is configured half duplex, the success rate is 10%. But the boot process does work 100% of the time when using WFTPD.  Any thoughts?

(https://wftpd-server.en.softonic.com/)

**Comment by giampaolo** [comment]
I'm not sure what to suggest. This looks like a connectivity problem rather than pyftpdlib's. Once you bind pyftpdlib on `0.0.0.0` (meaning all network interfaces) basically that's it. WFTPD or whatever does the same (bind a socket). Try to show your code.
