### ISSUE TITLE
About use in docker container

### ISSUE THREAD

**Issue by u-u-z** [giampaolo/pyftpdlib#459]
We try to use pyftpdlib in docker contianer...  But it can't useable in docker container.
here is link for Dockerfile [https://github.com/u-u-z/pyftpdlib-test/](https://github.com/u-u-z/pyftpdlib-test/)

It maybe wrong in our Dockerfile...
But we use the same( host environment ) method install it to docker container  in manual .
Many images have been tried, but without success. :-(

What's the happen go on  > <...

**Comment by u-u-z** [comment]
In ftp client ... it's response 257 "/" is the current directory.
It can't get the directory list.

**Comment by giampaolo** [comment]
Not sure about Docker, sorry, but I doubt this is a bug related to pyftpdlib. Closing.
