### ISSUE TITLE
Question: Ability to authorize by IP address?

### ISSUE THREAD

**Issue by talaniz** [giampaolo/pyftpdlib#460]
I would like to use this for a file sync project at work. We currently use WingFTP which allows us to authorize users, but also by IP address. Is there any functionality for this in the library?

**Comment by giampaolo** [comment]
Yes, you can override `FTPHandler.on_connect()` method in your subclass:
http://pyftpdlib.readthedocs.io/en/latest/tutorial.html#event-callbacks

**Comment by talaniz** [comment]
Thanks, I'll take a look! Closing out.
