### ISSUE TITLE
Callback Handler Request: on_file_delete and giving the user name on disconnect

### ISSUE THREAD

**Issue by diovudau** [giampaolo/pyftpdlib#462]
It would be nice to have more callbacks available. I am watching the users file systems and want to run filters under certain conditions.
One of the goals is to (re)-build a HTML audio player from a user uploaded directory of audio files. To keep that up to date I need to check more than just file uploads. 

1) on_file_delete is self explanatory. If the user deletes an audio file I need to rebuild the player

2) For performance reasons I could rebuild the player not on actual file changes but simply when the session ends. on_logout however is not a good choice because popular FTP clients (like filezilla) use only disconnect, not QUIT.   Seeing that the log already tells me which user disconnected I see the possibility to receive a username on_disconnect 

While I am at it.  You could provide the username on each callback. It doesn't hurt to know e.g. which user uploaded a file. I can do some python os.path magic to get the user from the path, but why not going the direct route?

**Comment by giampaolo** [comment]
From the handler class you can reference the username by using `self.username` attribute.
