### ISSUE TITLE
Tests fail to run when third-party pysendfile is not present on Python 3.3+

### ISSUE THREAD

**Issue by felixonmars** [giampaolo/pyftpdlib#465]
The tests seem to enforce pysendfile for posix even when os.sendfile is present:

```
pyftpdlib/test/__init__.py:40: in <module>
    import sendfile
E   ModuleNotFoundError: No module named 'sendfile'
```

**Comment by giampaolo** [comment]
I prefer the test to fail instead of not testing it without noticing. You are supposed to run `make setup-dev-env` before running tests.
