### ISSUE TITLE
Overwriting FS

### ISSUE THREAD

**Issue by BananaLoaf** [giampaolo/pyftpdlib#491]
I'm working on some project that overwrites all of the I/O functions, but the only thing I could not figure out is at what point do I intercept byte data that is coming from the user?

**Comment by giampaolo** [comment]
What do you mean?

**Comment by BananaLoaf** [comment]
I would like to pass bytes, received from user to my own function, that will write them into a file

**Comment by giampaolo** [comment]
Not sure what you mean.

**Comment by BananaLoaf** [comment]
Anyway, I figured it out. I'm creating a tempfile and writint user's data there and then mess with it how I desire. Sorry if my question was unclear, but It would be cool to have a byte buffer, that user writes into, and then it dumps to the file, so that people (me) could rewrite dump method the way they need. Currently user writes directly into file through fs.open and that's a little inconvenient, imo

**Comment by giampaolo** [comment]
If I understand your original question correctly:
> I'm working on some project that overwrites all of the I/O functions, but the only thing I could not figure out is at what point do I intercept byte data that is coming from the user?
...you're (possibly) talking about client upload (from client to server). The way that's implemented is:
- we read data from `DTPHandler`'s socket (`chunk = sock.recv()`)
- the chunks of data are written to a file object (`file.write(chunk)`)
- the file object is previously returned by `AbstractedFS.open` method which simply is a wrapper on top of `open()` builtin

I imagine you want to do something else other than writing on disk, so what you want to do is write a custom file-like class which provides the same interface of `open` builtin and which provides the same methods (read(), write(), close(), seek(), tell(), etc.). Specifically, if you want to do something else other than writing on disk the central method you want to customize is `write()`·
