### ISSUE TITLE
Small documentation typo

### ISSUE THREAD

**Issue by lurch** [giampaolo/pyftpdlib#502]
I just noticed that https://pyftpdlib.readthedocs.io/en/latest/faqs.html#which-python-versions-are-compatible says both "The latest version supporting Python 2.3 is pyftpdlib 1.4.0." and "The latest version supporting Python 2.3 is pyftpdlib 0.5.2." :wink: 

(and before you ask, I'm not interested in Python2.3, this just jumped out at me while looking at the FAQ)

**Comment by giampaolo** [comment]
Thanks, fixed. I have to make a big repolishing of doc and return working on pyftpdlib in general. Problem is I don't have enough time (psutil is takng most of it). =)
