### ISSUE TITLE
Creating FTP Virtual Directories

### ISSUE THREAD

**Issue by huyidao625** [giampaolo/pyftpdlib#503]
Hi Giampaolo:

How to create  FTP virtual directory？Does it support FTP virtual directories?

Like this :  [Creating FTP Virtual Directories](https://docs.microsoft.com/en-us/previous-versions/aa670206(v=vs.71))

thanks

**Comment by giampaolo** [comment]
I don't know what that MS page talks about (it looks quite old / no longer maintained). What I can tell you is that by default pyftpdlib provides `AbstractedFS`, which interacts with the real filesytem (a "disk") and nothing else, so whatever a virtual directory is you'll have to implement it from scratch.  =)

**Comment by lurch** [comment]
Having had a quick look at the `AbstractedFS` code, my naive guess is that it _might_ be possible to do what you want by simply creating a subclass of `AbstractedFS` and just overriding the "Pathname / conversion utilities" i.e. `ftpnorm`, `ftp2fs`, `fs2ftp` & `validpath` ?
