### ISSUE TITLE
mount directory to ftp server 

### ISSUE THREAD

**Issue by ErHaGo** [giampaolo/pyftpdlib#504]
can I mount a directory which outside the ftp home path to ftp server?
|----C:\ (Ftp Server)
|----D:\
|----E:\ 
that is ,is there some way to access D:\ or E:\ through ftp?
thanks

**Comment by giampaolo** [comment]
Of course you can. Check the examples in the doc where a user (with a given directory) is added to the authorizer.

**Comment by lurch** [comment]
Possibly related to #503 ?
