### ISSUE TITLE
FTP has no way to dynamically create new users and delete users after running

### ISSUE THREAD

**Issue by BingYanchi** [giampaolo/pyftpdlib#527]
Sometimes I need to add users and delete users while running.

Because of the blocking design, the while loop cannot be used to operate at runtime.
So I used multi-threaded operation, but when the newly added user logged in, the following error occurred:
```
Unhandled exception in thread started by <bound method ftp_server.run of <ftp_server.ftp_server object at 0x000001E2B15DC390>>
Traceback (most recent call last):
  File "C:\Users\Bing_Yanchi\Desktop\Ark\ftp\ftp_server.py", line 16, in run
    self.server.serve_forever()
  File "C:\Program Files\python\lib\site-packages\pyftpdlib\servers.py", line 245, in serve_forever
    self.ioloop.loop(timeout, blocking)
  File "C:\Program Files\python\lib\site-packages\pyftpdlib\ioloop.py", line 348, in loop
    poll(soonest_timeout)
  File "C:\Program Files\python\lib\site-packages\pyftpdlib\ioloop.py", line 446, in poll
    r, w, e = select.select(self._r, self._w, [], timeout)
OSError: [WinError 10038] An operation was attempted on a non-socket.
```

**Comment by AndreLaxe** [comment]
Check this post  : https://stackoverflow.com/a/24480146

You can create a class that run the server and add a _add_user_ function that you will call after the _run_ function.

```python
import thread

class ftp_server:
   def __init__(self):
       self.authorizer = DummyAuthorizer()
       self.authorizer.add_user('admin', 'password', '.', perm='elradfmwM')

   def run(self):
       self.handler = FTPHandler
       self.handler.authorizer = self.authorizer
       self.address = ('localhost', 21)
       self.server = FTPServer(self.address, self.handler)
       logging.basicConfig(filename='pyftpd.log', level=logging.INFO)
       self.server.serve_forever()

   def add_user(self,user,passwd,loc,privi):
       self.authorizer.add_user(str(user), str(passwd), str(loc), perm=str(privi))

this_ftp = ftp_server()

thread.Threading(this_ftp.run,()).start()
thread.Threading(this_ftp.add_user,('user','password',".",'elradfmwM')).start() #add user while server running
```

**Comment by BingYanchi** [comment]
> 检查这篇文章：[https](https://stackoverflow.com/a/24480146) : [//stackoverflow.com/a/24480146](https://stackoverflow.com/a/24480146)
> 
> 您可以创建一个运行服务器的类，并添加一个_add_user_函数，该函数将在_run_函数之后调用。
> 
> ```python
> 导入 线程
> 
> 类 ftp_server：
>     def  __init__（self）：
>         self。authorizer  =  DummyAuthorizer（）
>         自身。授权者。add_user（'admin'，'password'，'。'，perm = 'elradfmwM'）def run（self）：
>         self。handler = FTPHandler self。处理程序。授权者=
> 
>       
>          自我。授权者
>        自我。地址 =（'localhost'，21）
>         self。服务器 =  FTPServer的（自我。地址，自。处理程序）
>         的日志记录。basicConfig（文件名= 'pyftpd.log' ，水平= 日志记录。INFO）
>         自我。服务器。serve_forever（）def add_user（
> 
>     self，user，passwd，loc，privi）：
>         self。授权者。ADD_USER（STR（用户），STR（passwd中），STR（LOC），烫发= STR（Privi酒店））this_ftp = FTP_SERVER（）螺纹。超线程（this_ftp。运行，（））。start（）
>  线程。穿线
> 
>   
> 
> （this_ftp。ADD_USER，（'用户'，'密码'，“” ，'elradfmwM' ））。start（）＃在服务器运行时添加用户
> ```

Are you sure this is Python 3 instead of Python 2?

**Comment by BingYanchi** [comment]
> Check this post : https://stackoverflow.com/a/24480146
> 
> You can create a class that run the server and add an _add_user_ function that you will call after the _run_ function.
> 
> ```python
> import thread
> 
> class ftp_server:
>    def __init__(self):
>        self.authorizer = DummyAuthorizer()
>        self.authorizer.add_user('admin', 'password', '.', perm='elradfmwM')
> 
>    def run(self):
>        self.handler = FTPHandler
>        self.handler.authorizer = self.authorizer
>        self.address = ('localhost', 21)
>        self.server = FTPServer(self.address, self.handler)
>        logging.basicConfig(filename='pyftpd.log', level=logging.INFO)
>        self.server.serve_forever()
> 
>    def add_user(self,user,passwd,loc,privi):
>        self.authorizer.add_user(str(user), str(passwd), str(loc), perm=str(privi))
> 
> this_ftp = ftp_server()
> 
> thread.Threading(this_ftp.run,()).start()
> thread.Threading(this_ftp.add_user,('user','password',".",'elradfmwM')).start() #add user while server running
> ```

Are you sure this is Python 3 instead of Python 2?

**Comment by AndreLaxe** [comment]
Yep. It works with Python 3.

**Comment by BingYanchi** [comment]
> Yep. It works with Python 3.

But are you sure Python 3 can import thread?

Is it that I need to install a certain library?

**Comment by lurch** [comment]
https://docs.python.org/2/library/thread.html says:
"Note The `thread` module has been renamed to `_thread` in Python 3. The `2to3` tool will automatically adapt imports when converting your sources to Python 3; however, you should consider using the high-level `threading` module instead."

**Comment by BingYanchi** [comment]
> https://docs.python.org/2/library/thread.html says:
> "Note The `thread` module has been renamed to `_thread` in Python 3. The `2to3` tool will automatically adapt imports when converting your sources to Python 3; however, you should consider using the high-level `threading` module instead."

```python
import threading
from pyftpdlib.authorizers import DummyAuthorizer
from pyftpdlib.handlers import FTPHandler
from pyftpdlib.servers import FTPServer

class ftp_server(threading.Thread):
   def __init__(self):
       super(ftp_server, self).__init__(name='ftp_server')
       self.authorizer = DummyAuthorizer()
       self.authorizer.add_user('admin', 'password', '.', perm='elradfmwM')
       
   def run(self):
       self.handler = FTPHandler
       self.handler.authorizer = self.authorizer
       self.address = ('localhost', 21)
       self.server = FTPServer(self.address, self.handler)
       self.server.serve_forever()

   def add_user(self,user,passwd,loc,privi):
       self.authorizer.add_user(str(user), str(passwd), str(loc), perm=str(privi))

if __name__ == '__main__':
    ftp_server().start
    ftp_server.add_user('user','password',".",'elradfmwM').start
```

```
PS D:\Github\ArkManager> & "C:/Program Files/python/python.exe" d:/Github/ArkManager/python/ftp.py
Traceback (most recent call last):
  File "d:/Github/ArkManager/python/ftp.py", line 24, in <module>
    ftp_server.add_user('user','password',".",'elradfmwM').start
TypeError: add_user() missing 1 required positional argument: 'privi'
```

I don't know how to solve this `self` problem.

**Comment by giampaolo** [comment]
You are not instantiating `ftp_server` class correctly. Instead of:

```python
if __name__ == '__main__':
    ftp_server().start
    ftp_server.add_user('user','password',".",'elradfmwM').start
```

...do (not tested):

```python
if __name__ == '__main__':
    server = ftp_server()
    server.add_user('user','password',".",'elradfmwM')
    server.start()
```

You don't need to inherit from `threading.Thread` though. I'm not sure what you're aiming at exactly.

**Comment by BingYanchi** [comment]
> You are not instantiating `ftp_server` class correctly. Instead of:
> 
> ```python
> if __name__ == '__main__':
>     ftp_server().start
>     ftp_server.add_user('user','password',".",'elradfmwM').start
> ```
> 
> ...do (not tested):
> 
> ```python
> if __name__ == '__main__':
>     server = ftp_server()
>     server.add_user('user','password',".",'elradfmwM')
>     server.start()
> ```
> 
> You don't need to inherit from `threading.Thread` though. I'm not sure what you're aiming at exactly.

Thank! Perfectly solved my problem.
