### ISSUE TITLE
Move received file to final destination only after writing is complete?

### ISSUE THREAD

**Issue by coproc** [giampaolo/pyftpdlib#557]
When another application polls a directory, into which the FTP server writes a file: is there a possibility to check whether the file is completly written? A simple solution would be that the FTP servers downloads the file's content to a temporary file, which is moved to the final destination only after having received the complete data. Is something like this possible with pyftpdlib?

**Comment by giampaolo** [comment]
Take a look at the docs. There are callback methods of FTPHandler class that are invoked on successful download/upload. You can override them and put logic in there.

**Comment by coproc** [comment]
Thanks! That will help to solve the problem.
