### ISSUE TITLE
server.close_all() freeze the whole application

### ISSUE THREAD

**Issue by GianptDev** [giampaolo/pyftpdlib#577]
System: Linux Mint 20.4
Python 3.10.5

I've made a gui application for a simple ftp interface, the application run the server inside a thread.
This is the code of the button:

	def stop_server(self) -> None:
		server = self.server
		self.server = None

		server.close_all()
		self.server_thread.join()
		
		self.server_thread = None

If I execute this script on windows and i press the button it will work normally.
If I execute this script on Mint it will freeze the whole application.

**Comment by giampaolo** [comment]
Closing as outdated.
