### ISSUE TITLE
How to custom logging

### ISSUE THREAD

**Issue by wfeng66** [giampaolo/pyftpdlib#589]
Hello,

I appreciate your great job. It's a nice product. 

The password in log is marked out. How can I change it to show the password? The second is I need to extract some information in the datagram, for instance, TTL. Where would be a good place to extract and log?

Thanks,
Wei

**Comment by giampaolo** [comment]
Password is hidden on purpose:
https://github.com/giampaolo/pyftpdlib/blob/3d3ef0ba04d5b0b06711413415b391eaefa42bb4/pyftpdlib/handlers.py#L1591-L1594
If you want to show it you have to do it in your own `FTPHandler` subclass.
