### ISSUE TITLE
Question: limit Max upload/download speed for user accounts

### ISSUE THREAD

**Issue by honglei** [giampaolo/pyftpdlib#598]
1）Max upload speed for user accounts
Limits the maximum upload bandwidth shared between all sessions associated with an individual User account. Setting a limit of 0 KB/s means unlimited bandwidth.

2） Max download speed for user accounts
Limits the maximum download bandwidth shared between all sessions associated with an individual user account. Setting a limit of 0 KB/s means unlimited bandwidth.

**Comment by giampaolo** [comment]
See: https://pyftpdlib.readthedocs.io/en/latest/tutorial.html#throttle-bandwidth.
