### ISSUE TITLE
FTP server stuck

### ISSUE THREAD

**Issue by ttkrpink** [giampaolo/pyftpdlib#617]
Running FTPServer inside Django, 
And Django Running inside a docker container. 

My setup is very simple. 

When I ftp from windows cmd. Login is ok, CD is ok. "ls" stuck, “get” stuck with the same error message.

I think the permission is fine. and Login with root. I tried running it outside docker container. The result is the same: 150 File status okay. About to open data connection.

Any help is appreciated.

Thanks

```
ftp> ls
150 File status okay. About to open data connection.
```
![image](https://github.com/giampaolo/pyftpdlib/assets/2522889/75a6911c-6fe8-4e6e-8f99-aed3d993b518)

**Comment by xillmera** [comment]
Simular. Probably, last ver is broken. 
I have next output after EPRT comm.:
`[D 2023-11-12 16:55:24] [debug] call: close() (<pyftpdlib.handlers.ActiveDTP *.*.*.*:48481 at 0x7f1e553a9a20>)`

**Comment by xillmera** [comment]
[this fact](https://superuser.com/a/1386069) means, that it is necessary to have range of passive ports. Problem can be solved by line from [docs](https://pyftpdlib.readthedocs.io/en/latest/tutorial.html?highlight=Passive%20ports#a-base-ftp-server)
'handler.passive_ports = range(60000, 65535)'
and open range of ports in firewall 'ufw allow 60000:65535/tcp'

**Comment by giampaolo** [comment]
Indeed `EPRT` / `PORT` active data connection is usually not recommended, because the client needs to have an open port / port forwarding for the incoming connection. EPSV / PASV should be instead. Closing.
