### ISSUE TITLE
Python blocks all disk access when no space left on device

### ISSUE THREAD

**Issue by rvdrijst** [giampaolo/pyftpdlib#619]
We're running into issues when the disk runs out of space while uploading.

The disk we're using is an xfs network volume that is mounted to a particular directory that the ftp server has access to.

Everything works fine until the disk is full: all access to the disk is frozen. `df -h` hangs _or_ shows space that is not actually available (after reboot it shows 0). Normal reboot doesn't work, we have to restart the VPS through the management console, and run `xfs_repair` on the disk to get it working again.

This was not an issue with the 'normal' FTP server. We added `pyftpdlib` to add some custom authentication and everything is working very well, until the disk is full (happens a few times a month).

It seems that python is somehow not releasing access to the filesystem when this happens, but I don't see why.
Any help would be greatly appreciated. If there are other logs that I can upload that would help, let me know.

In the console of the VPS (before rebooting)
![Screenshot 2024-01-24 at 15 17 30](https://github.com/giampaolo/pyftpdlib/assets/98135/c025545b-93e9-416c-bd1b-b6f6d7933c33)

Logs of the ftp service:
![Screenshot 2024-01-24 at 15 23 55](https://github.com/giampaolo/pyftpdlib/assets/98135/b0db121a-5a66-4f25-8f27-cc77e227bb14)

**Comment by giampaolo** [comment]
What do you mean exactly by "blocks disk access"? That the FTP server gets stuck and does nothing?

Note: pyftpdlib is a non-blocking server. It doesn't play nice with NFS / network directories. It will block. So you probably want to use the thread-FTP server variant instead:
https://pyftpdlib.readthedocs.io/en/latest/tutorial.html#changing-the-concurrency-model

**Comment by giampaolo** [comment]
>  Rebooting doesn't work either because it's waiting for the filesystem to be released. 

Wow. This sounds like a much bigger problem then.
Closing this out since it doesn't seem related to pyftpdlib per se.
