### ISSUE TITLE
how to detect file up load is not completed

### ISSUE THREAD

**Issue by eragondr** [giampaolo/pyftpdlib#624]
Hi. I need to check that the file user upload to the server is completed or not. if not it will be removed.
As I check in the code it said if the file is receive it always return transfer_finished = True. What logic I can implements to solve the problem .
![image](https://github.com/giampaolo/pyftpdlib/assets/28474355/8b55b722-e1be-4e6a-8044-a422f73bb68a)

Thank you for your works

**Comment by giampaolo** [comment]
You should use: https://pyftpdlib.readthedocs.io/en/latest/tutorial.html#event-callbacks

**Comment by eragondr** [comment]
hi 
the problem is it never going to on_incomplete_file_received
