### ISSUE TITLE
Duplicate keycert.pem

### ISSUE THREAD

**Issue by davetapley** [giampaolo/pyftpdlib#644]
I just ran in to `ee key too small`, which confused me because 99b055b6e9fcfffccb1e4e7c71cef0ca96f37c3e should have fixed it

Turns out there are two `keycert.pem`, 99b055b6e9fcfffccb1e4e7c71cef0ca96f37c3e updated one in `/test/` but docs point to copy in `/demo/`:
https://github.com/giampaolo/pyftpdlib/blob/66c89850ffc50e8764502a482df06bbac07b07ef/docs/tutorial.rst?plain=1#L441

---

Happy to do PR, do you prefer:

a. Updating docs to point to one in `/test` and delete one in `/demo`, or:
b. Update one in `/demo` to match 99b055b6e9fcfffccb1e4e7c71cef0ca96f37c3e?

**Comment by giampaolo** [comment]
Hi. Thanks, good catch. I think we should do B.
